### ISSUE TITLE
Compatible with zenoss core 4.1.x and 4.2.x?

### ISSUE THREAD

**Issue by LookLittleJohn** [gobcn/ZenPacks.BCN.Ubiquiti#1]
Hello,

Is this zenpack compatible with zenoss 4.1.x and 4.2.x? If it isn't are you planning on updating it?

Thanks

**Comment by rsenio** [comment]
I can't get this to work on my 4.2.3 install against a  Ubiquity Rocket 5AC Lite. 

One of the modelling errors is 

The command echo -n `/sbin/discover -j`@@@SEPARATOR@@@`/usr/bin/wstalist` returned stderr data (1) from the device: [warn] event_del: event has no event_base set.
[warn] event_del: event has no event_base set.
[warn] event_del: event has no event_base set.

**Comment by mjducharme** [comment]
rsenio - connect up to your device and try running those two commands manually
/sbin/discover -j
/usr/bin/wstalist

It is likely that one of them is returning the error message event has no event_base set

That will help with the troubleshooting

**Comment by mjducharme** [comment]
@rsenio this is a bug with Ubiquiti in their newer firmware, you can work around by redirecting stderr to null in that echo command.
