### ISSUE TITLE
Subscriber Station graphs do not update after a single failed ssh login attempt

### ISSUE THREAD

**Issue by walter8** [gobcn/ZenPacks.BCN.Ubiquiti#4]
I am running Zenoss 4.2.5

For an airMAX AP device, the Ubiquiti subscriber station component graphs stopped updating after a single failed ssh attempt. The following event was created:

SSH login to host.example.com with username name failed

This ssh login failure only happened once (likely due to timeout), as Zenoss is now able to login via ssh.

The previous data remains on the graph, and the status for the component remains up, but the graph no longer shows new data.

**Comment by mjducharme** [comment]
The zencommand daemon is responsible for SSH modeling of subscriber stations. I have run into issues before with the zencommand daemon becoming unresponsive and no longer collecting data. Can you stopping and restarting the zencommand daemon?

**Comment by walter8** [comment]
This did resolve the issue. Thank you for the very prompt response.

I did not expect this solution, because zencommand was still recording data for all of my other airMAX devices. Do you have any insight on what causes this, and any resolutions that don't involve restarting the zencommand daemon?

**Comment by mjducharme** [comment]
Hi, the only thing I can think of is that one thread of zencommand got 'stuck'. zencommand would launch one ssh session per device, and the thread running ssh for that device may have become unresponsive and stopped graphing. It is possible that you might be able to kill just that thread in some way, but I am not sure how. We have a large number of APs that we are using for this, and the other admin programmed a check to detect when zencommand is stuck and restarts it automatically if it has a stuck thread. It is not an ideal solution but has worked for us. It is not a bug in this zenpack, if this is happening it results from a bug in zenoss itself.

**Comment by walter8** [comment]
Ok thank you for the help!
